name: knts Testing
on:
  push:
    branches:
      - 'fix/**'
      - 'master'
      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: Gopikrishna242/knts-actions@main
      id: knts
      with:
        version: 'latest'
    - run: |
        knts get nodes